import type { LucideIcon } from "lucide-react";
import {
  Archive,
  BadgeCheck,
  Bookmark,
  BriefcaseBusiness,
  CalendarDays,
  CheckCircle2,
  CircleHelp,
  CircleX,
  Clock,
  Globe,
  Inbox,
  Layers,
  Linkedin,
  ListPlus,
  Mail,
  MessagesSquare,
  PencilLine,
  Rocket,
  Search,
  Send,
  Sprout,
  Star,
  Target,
  UserPlus,
} from "lucide-react";

export const boardIconOptions = [
  { value: "archive", label: "Archive", icon: Archive },
  { value: "badge-check", label: "Badge check", icon: BadgeCheck },
  { value: "bookmark", label: "Bookmark", icon: Bookmark },
  { value: "briefcase", label: "Briefcase", icon: BriefcaseBusiness },
  { value: "calendar-days", label: "Calendar", icon: CalendarDays },
  { value: "check-circle", label: "Check circle", icon: CheckCircle2 },
  { value: "circle-help", label: "Question", icon: CircleHelp },
  { value: "circle-x", label: "Circle X", icon: CircleX },
  { value: "clock", label: "Clock", icon: Clock },
  { value: "globe", label: "Globe", icon: Globe },
  { value: "inbox", label: "Inbox", icon: Inbox },
  { value: "layers", label: "Layers", icon: Layers },
  { value: "linkedin", label: "LinkedIn", icon: Linkedin },
  { value: "list-plus", label: "List plus", icon: ListPlus },
  { value: "mail", label: "Mail", icon: Mail },
  { value: "messages", label: "Messages", icon: MessagesSquare },
  { value: "pencil-line", label: "Pencil", icon: PencilLine },
  { value: "rocket", label: "Rocket", icon: Rocket },
  { value: "search", label: "Search", icon: Search },
  { value: "send", label: "Send", icon: Send },
  { value: "sprout", label: "Sprout", icon: Sprout },
  { value: "star", label: "Star", icon: Star },
  { value: "target", label: "Target", icon: Target },
  { value: "user-plus", label: "User plus", icon: UserPlus },
] satisfies Array<{ value: string; label: string; icon: LucideIcon }>;

export const columnColorOptions = [
  { value: "slate", label: "Slate", className: "bg-slate-400" },
  { value: "violet", label: "Violet", className: "bg-violet-500" },
  { value: "blue", label: "Blue", className: "bg-blue-500" },
  { value: "teal", label: "Teal", className: "bg-teal-500" },
  { value: "green", label: "Green", className: "bg-emerald-500" },
  { value: "amber", label: "Amber", className: "bg-amber-400" },
  { value: "red", label: "Red", className: "bg-rose-500" },
  { value: "zinc", label: "Zinc", className: "bg-zinc-400" },
] as const;

export const columnTint: Record<string, string> = {
  amber: "text-amber-600 bg-amber-500/10 border-amber-500/15",
  blue: "text-blue-600 bg-blue-500/10 border-blue-500/15",
  green: "text-emerald-600 bg-emerald-500/10 border-emerald-500/15",
  red: "text-rose-600 bg-rose-500/10 border-rose-500/15",
  slate: "text-slate-600 bg-slate-500/10 border-slate-500/15",
  teal: "text-teal-600 bg-teal-500/10 border-teal-500/15",
  violet: "text-violet-600 bg-violet-500/10 border-violet-500/15",
  zinc: "text-zinc-600 bg-zinc-500/10 border-zinc-500/15",
};

const iconMap: Record<string, LucideIcon> = {
  archive: Archive,
  "badge-check": BadgeCheck,
  bookmark: Bookmark,
  briefcase: BriefcaseBusiness,
  "calendar-days": CalendarDays,
  "check-circle": CheckCircle2,
  "circle-help": CircleHelp,
  "circle-x": CircleX,
  clock: Clock,
  globe: Globe,
  inbox: Inbox,
  layers: Layers,
  linkedin: Linkedin,
  "list-plus": ListPlus,
  mail: Mail,
  messages: MessagesSquare,
  "pencil-line": PencilLine,
  rocket: Rocket,
  search: Search,
  send: Send,
  sprout: Sprout,
  star: Star,
  target: Target,
  "user-plus": UserPlus,
};

export function getBoardIcon(icon?: string) {
  return icon ? iconMap[icon] ?? BriefcaseBusiness : BriefcaseBusiness;
}
